server:
  port: 8080

spring:
  application:
    name: ipos-backend

  datasource:
    url: jdbc:mysql://mysql:3306/ipos_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ipospu26@gmail.com
    password: czmkgqcciiabngjm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

stripe:
  secret-key: