import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import './LoginPage.css';

const API = 'http://localhost:8080';

function ChangePasswordModal({ email, onComplete }) {
  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (newPassword !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }
    if (newPassword.length < 6) {
      setError('Password must be at least 6 characters.');
      return;
    }

    setLoading(true);
    try {
      const res = await fetch(`${API}/auth/change-password`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, currentPassword, newPassword }),
      });
      const data = await res.json();
      if (data.success) {
        onComplete();
      } else {
        setError(data.message || 'Failed to change password.');
      }
    } catch {
      setError('Could not connect to server.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-card">
        <div className="login-header">
          <h2>Change Your Password</h2>
        </div>
        <p style={{ color: '#666', fontSize: '0.9rem', marginBottom: '1rem' }}>
          You must change your password before continuing.
        </p>

        {error && <p className="login-error">{error}</p>}

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label>Current Password</label>
            <input
              type="password"
              placeholder="Enter your current password"
              value={currentPassword}
              onChange={e => setCurrentPassword(e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label>New Password</label>
            <input
              type="password"
              placeholder="Enter new password (min 6 chars)"
              value={newPassword}
              onChange={e => setNewPassword(e.target.value)}
              required
            />
          </div>
          <div className="form-group">
            <label>Confirm New Password</label>
            <input
              type="password"
              placeholder="Confirm new password"
              value={confirmPassword}
              onChange={e => setConfirmPassword(e.target.value)}
              required
            />
          </div>
          <button type="submit" className="login-submit-btn" disabled={loading}>
            {loading ? 'Changing...' : 'Change Password'}
          </button>
        </form>
      </div>
    </div>
  );
}

function LoginPage() {
  const navigate = useNavigate();
  const { login, forcePasswordChange, clearForcePasswordChange, userEmail } = useAuth();
  const [isRegister, setIsRegister] = useState(false);
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    confirmPassword: '',
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [showPasswordChange, setShowPasswordChange] = useState(false);
  const [pendingEmail, setPendingEmail] = useState('');

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    if (isRegister) {
      // Non-commercial registration: only needs email
      // Password is auto-generated by the backend and emailed
      try {
        const response = await fetch(`${API}/auth/register`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email: formData.email }),
        });

        const data = await response.json();
        if (data.success) {
          setSuccess(data.message);
          setIsRegister(false);
          setFormData({ email: formData.email, password: '', confirmPassword: '' });
        } else {
          setError(data.message || 'Registration failed');
        }
      } catch {
        setError('Could not connect to the server.');
      }
    } else {
      // Login
      try {
        const response = await fetch(`${API}/auth/login`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'include',
          body: JSON.stringify({
            email: formData.email,
            password: formData.password,
          }),
        });

        const data = await response.json();
        if (data.success) {
          if (data.forcePasswordChange) {
            // Must change password before proceeding
            setPendingEmail(data.email);
            setShowPasswordChange(true);
            login(data.email, data.merchant, true);
          } else {
            login(data.email, data.merchant, false);
            navigate('/');
          }
        } else {
          setError(data.message || 'Login failed');
        }
      } catch {
        setError('Could not connect to the server.');
      }
    }
  };

  // Show password change modal if needed
  if (showPasswordChange || forcePasswordChange) {
    return (
      <ChangePasswordModal
        email={pendingEmail || userEmail}
        onComplete={() => {
          setShowPasswordChange(false);
          clearForcePasswordChange();
          navigate('/');
        }}
      />
    );
  }

  return (
    <div className="login-page">
      <div className="login-card">
        <div className="login-header">
          <h2>{isRegister ? 'Create Account' : 'Sign In'}</h2>
        </div>

        {error && <p className="login-error">{error}</p>}
        {success && <p className="login-success">{success}</p>}

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="email">Email Address</label>
            <input
              type="email"
              id="email"
              name="email"
              placeholder="you@example.com"
              value={formData.email}
              onChange={handleChange}
              required
            />
          </div>

          {!isRegister && (
            <div className="form-group">
              <label htmlFor="password">Password</label>
              <input
                type="password"
                id="password"
                name="password"
                placeholder="Enter your password"
                value={formData.password}
                onChange={handleChange}
                required
              />
            </div>
          )}

          {isRegister && (
            <p style={{ color: '#666', fontSize: '0.85rem', margin: '0.5rem 0 1rem' }}>
              A password will be generated and sent to your email address.
              You will be asked to change it on your first login.
            </p>
          )}

          <button type="submit" className="login-submit-btn">
            {isRegister ? 'Register' : 'Sign In'}
          </button>
        </form>

        <div className="login-divider">
          <span>or</span>
        </div>

        <div className="login-switch">
          {isRegister ? (
            <p>Already have an account? <button onClick={() => { setIsRegister(false); setError(''); setSuccess(''); }} className="switch-btn">Sign In</button></p>
          ) : (
            <p>Don't have an account? <button onClick={() => { setIsRegister(true); setError(''); setSuccess(''); }} className="switch-btn">Create Account</button></p>
          )}
        </div>
      </div>
    </div>
  );
}

export default LoginPage;
